### ISSUE TITLE
The pledges with a beneficiary appear under the "Pledges créés" section not under the "Pledges affectés"

### ISSUE THREAD

**Issue by xavigonz** [pledgcorporate/web#6] opened 2016-01-15 22:37 UTC

**Comment by yangeorget** [comment] 2016-01-16 12:26
Unclear but not a bug.
Pledges created means pledges created by the user (assigned or not).
Pledges assigned means pledges assigned to the user (not created by him/her).

**Closed by yangeorget** 2016-01-16 12:26 UTC

**Comment by xavigonz** [comment] 2016-01-16 13:56
Ok understood
